name: No-Op Workflow

on:
  push:
    branches:
      - main

jobs:
  noop:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Do nothing
        run: echo "This is a no-op workflow that does nothing."
